server:
  port: 8888
spring:
  security:
    user:
      name: root
      password: s3cr3t
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hexaforce/config-repo.git
          basedir: target/config
