server:
  port: 8888

encrypt:
  key-store:
    alias: config-server-key
    location: classpath:/config-server.jks
    password: my-s70r3-s3cr3t
    secret: my-k34-s3cr3t
spring:
  security:
    user:
      name: root
      password: s3cr3t
  rabbitmq:
    host: localhost
    port: 5672
    username: vagrant
    password: vagrant
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hexaforce/config-repo.git
          basedir: target/config
