info:
  component: Config Server
server:
  port: 8888
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hexaforce/config-repo.git
          basedir: target/config
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    status-page-url-path: /admin/info
    health-check-url-path: /admin/health
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/