logging:
  level:
    org:
      springframework:
        web: DEBUG
  pattern:
    level: '%d{ABSOLUTE} [%X{X-B3-TraceId}/%X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n'
spring:
  sleuth:
    sampler:
      probability: 1.0
    traceId128: true
