spring:
  session:
    store-type: redis
  security:
    user:
      password: password
#    ignored: "*.bundle.*"
zuul:
  routes:
    resource:
      path: /resource/**
      url: https://localhost:9000
      sensitive-headers:
    