info:
  component: Zuul Server
server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

security:
  user:
    password: password
  ignored:
  - "*.bundle.*"
spring:
  session:
    store-type: redis
zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:8765
      sensitive-headers:
    