server:
  port: 8989

logging:
  level:
    root: INFO
    com.netflix.discovery: 'OFF'
    # org.springframework.integration: DEBUG

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    non-secure-port: 8989
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    