info:
  component: Zuul Server

endpoints:
  restart:
    enabled: true

zuul:
  ignoredServices: "*"
  routes:
    productcomposite:
      path: /productcomposite/**
#      stripPrefix: false

server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
