spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/authentication?useSSL=false&useUnicode=true&characterEncoding=utf8'
    password: password
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
