server:
  port: 8888

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: vagrant
    password: vagrant
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hexaforce/config-repo.git
          basedir: target/config
